"""
This script places the conus label (60) on the centerline at a known S-I level (world Z, in mm), for example the conus
level identified on the high-resolution CISS image. Any existing label 60 is replaced; the PMJ label (50) is kept.

The conus is placed on the centerline slice closest to the given Z (if the traced centerline does not reach that
level, the centerline is extended by continuing its last segment, as in 02_compute_cord_length.py). Only the S-I position of the label is used by 02_compute_cord_length.py.

Input:
    - labels file with the PMJ (label 50), modified in place
    - centerline CSV file generated by sct_get_centerline (physical space, mm)
    - conus world Z (mm)

The script is called by 01_label_centerline_pmj_conus.sh and requires the SCT conda environment to be activated:
    source ${SCT_DIR}/python/etc/profile.d/conda.sh
    conda activate venv_sct

Example:
    python 01a_place_conus_from_ciss.py -labels sub-ltr03_ses-03_acq-localizerSag_T2w_label-PMJtip_dlabel.nii.gz
    -centerline sub-ltr03_ses-03_acq-localizerSag_T2w_label-centerline.csv -z -402.5

Authors: Elia Rochiccioli, Jan Valosek
"""

import argparse
import numpy as np
from scipy.interpolate import interp1d

from spinalcordtoolbox.image import Image

CONUS_LABEL = 60


def main():
    parser = argparse.ArgumentParser(description='Place the conus label (60) on the centerline at a known S-I level.')
    parser.add_argument('-labels', required=True, help='Labels file (modified in place).')
    parser.add_argument('-centerline', required=True, help='Centerline CSV file generated by sct_get_centerline.')
    parser.add_argument('-z', type=float, required=True, help='Conus world Z (mm).')
    args = parser.parse_args()

    # Centerline point at the conus level (linear interpolation, or extrapolation of the last segment)
    centerline = np.loadtxt(args.centerline, delimiter=',', ndmin=2)
    centerline = centerline[np.argsort(centerline[:, 2])]   # sort from inferior to superior
    z = centerline[:, 2]
    point = interp1d(z, centerline, axis=0, fill_value='extrapolate')(args.z)
    if not z.min() <= args.z <= z.max():
        print(f'WARNING: the centerline does not reach the conus level (Z={args.z} mm, centerline Z range '
              f'{z.min():.1f} to {z.max():.1f} mm). Consider tracing the centerline further.')

    # Replace the conus label
    img = Image(args.labels)
    vox = img.transfo_phys2pix([point])[0]   # rounded to the nearest voxel
    vox = np.clip(vox, 0, np.array(img.data.shape) - 1)
    img.data[img.data == CONUS_LABEL] = 0
    img.data[tuple(vox)] = CONUS_LABEL
    img.save()
    print(f'Conus ({CONUS_LABEL}) placed at voxel {vox.tolist()} (Z={args.z} mm) in {args.labels}')


if __name__ == '__main__':
    main()
