"""
This script merges the centerline, the PMJ and the conus into a single file to show them in a single sagittal QC entry
(sct_qc -p sct_label_vertebrae, which displays a sagittal slice following the centerline).

The PMJ and the conus are drawn as short horizontal (A-P) ticks on the centerline at their S-I level, i.e., at the
levels used to compute the cord length (02_compute_cord_length.py uses only the S-I position of the labels). Drawing
them on the centerline (rather than at their own position) keeps them visible on the sagittal slice following the
centerline.

Output values: 1 = centerline, 2 = PMJ, 3 = conus. Consecutive values get distinct colors in the SCT QC.

Input:
    - centerline NIfTI file generated by sct_get_centerline
    - labels file with the PMJ (label 50) and the conus (label 60)

The script is called by 01_label_centerline_pmj_conus.sh and requires the SCT conda environment to be activated:
    source ${SCT_DIR}/python/etc/profile.d/conda.sh
    conda activate venv_sct

Example:
    python 01b_merge_labels_for_qc.py -centerline sub-ltr13_ses-03_acq-localizerSag_T2w_label-centerline.nii.gz
    -labels sub-ltr13_ses-03_acq-localizerSag_T2w_label-PMJtip_dlabel.nii.gz -o sub-ltr13_merged.nii.gz

Author: Jan Valosek
"""

import argparse
import numpy as np

from spinalcordtoolbox.image import Image

# Input label value -> output value
LABELS = {50: 2,    # PMJ
          60: 3}    # conus
TICK_HALF_WIDTH = 4     # voxels on each side of the centerline in the A-P direction


def main():
    parser = argparse.ArgumentParser(description='Merge the centerline, the PMJ and the conus into a single file for '
                                                 'a sagittal QC.')
    parser.add_argument('-centerline', required=True, help='Centerline NIfTI file generated by sct_get_centerline.')
    parser.add_argument('-labels', required=True, help='Labels file with the PMJ (50) and the conus (60).')
    parser.add_argument('-o', required=True, help='Output file.')
    args = parser.parse_args()

    # RPI: x = R-L, y = A-P, z = S-I
    im_centerline = Image(args.centerline)
    native_orientation = im_centerline.orientation
    im_centerline.change_orientation('RPI')
    im_labels = Image(args.labels).change_orientation('RPI')

    im_out = im_centerline.copy()
    im_out.data = (im_centerline.data > 0).astype(np.uint8)     # 1 = centerline
    x, y, z = np.nonzero(im_centerline.data)
    for value_in, value_out in LABELS.items():
        z_label = np.argwhere(im_labels.data == value_in)[0][2]
        i = np.argmin(np.abs(z - z_label))      # centerline voxel at the label S-I level (nearest if outside the range)
        y_min = max(y[i] - TICK_HALF_WIDTH, 0)
        im_out.data[x[i], y_min:y[i] + TICK_HALF_WIDTH + 1, z_label] = value_out

    im_out.change_orientation(native_orientation).save(args.o, dtype='uint8')


if __name__ == '__main__':
    main()
