"""
This script computes the spinal cord length from the pontomedullary junction (PMJ) to the conus (cord tip) on the
whole-spine sagittal localizer.

The length is measured along the manual centerline (generated by 01_label_centerline_pmj_conus.sh) between the S-I
levels of the PMJ (label 50) and the conus (label 60). Only the S-I position of the labels is used: the labels may sit
on a different sagittal slice than the centerline, and using their R-L/A-P position would add a spurious offset that is
not cord length. If the centerline does not reach the PMJ or the conus level, it is extended by continuing its last
segment (see the 'centerline_extrap_mm' column).

Optionally (-smooth), the R-L and A-P coordinates of the centerline are smoothed with a moving average along the S-I
axis before computing the length, to remove click tremor that would otherwise inflate the length of a jagged trace.

The continuous centerline in the CSV file (written by sct_get_centerline) is used instead of the centerline NIfTI file:
the localizer has only a few 5 mm thick sagittal slices, so the NIfTI centerline is discretized into large R-L steps.

Input:
    - folder with the manual labels (typically derivatives/labels), containing for each subject:
        sub-*/ses-*/anat/*_label-centerline.csv: centerline in physical space (RAS, mm), one point per axial slice
        sub-*/ses-*/anat/*_label-PMJtip_dlabel.nii.gz: PMJ (label 50) and conus (label 60)

Output (saved to the input folder by default, see -o):
    - cord_length.csv: for each subject, the cord length along the centerline (cord_length_mm), the straight S-I
      distance between the PMJ and the conus (si_distance_mm), and how far the centerline was extended beyond its
      traced range (centerline_extrap_mm)

The script requires the SCT conda environment to be activated:
    source ${SCT_DIR}/python/etc/profile.d/conda.sh
    conda activate venv_sct

Example:
    python 02_compute_cord_length.py -i ~/data/balgrist/14_LTR/bids/derivatives/labels
    python 02_compute_cord_length.py -i ~/data/balgrist/14_LTR/bids/derivatives/labels -smooth 5

Authors: Elia Rochiccioli, Jan Valosek
"""

import os
import glob
import argparse
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

from spinalcordtoolbox.image import Image

PMJ_LABEL = 50
CONUS_LABEL = 60


def get_label_z(img, value):
    """
    Get the S-I position (in mm, physical space) of a single-voxel label.
    :param img: Image with the labels
    :param value: label value
    :return: z coordinate in mm (None if the label is missing or not a single voxel)
    """
    vox = np.argwhere(img.data == value)
    if len(vox) != 1:
        print(f'  Expected 1 voxel with label {value}, found {len(vox)}.')
        return None
    return img.transfo_pix2phys([vox[0]])[0][2]


def smooth_centerline(centerline, window):
    """
    Smooth the R-L and A-P coordinates of the centerline with a moving average along the S-I axis.
    The window//2 points at each end are kept unchanged (the moving average is not defined there).
    :param centerline: nx3 array with the centerline points sorted along the S-I axis
    :param window: moving average window in number of points (one point per slice)
    :return: smoothed centerline
    """
    half = window // 2
    smoothed = centerline.copy()
    for i in (0, 1):    # R-L and A-P; the S-I coordinate is kept
        smoothed[half:-half, i] = np.convolve(centerline[:, i], np.ones(window) / window, mode='valid')
    return smoothed


def compute_length(centerline, z_bottom, z_top, smooth=0):
    """
    Compute the length along the centerline between two S-I levels.
    :param centerline: nx3 array with the centerline points in physical space (mm)
    :param z_bottom: S-I level of the bottom end (mm)
    :param z_top: S-I level of the top end (mm)
    :param smooth: moving average window (number of points) to smooth the centerline; 0 = no smoothing
    :return: length in mm
    """
    centerline = centerline[np.argsort(centerline[:, 2])]   # sort from inferior to superior
    if smooth > 1 and len(centerline) > smooth:
        centerline = smooth_centerline(centerline, smooth)
    z = centerline[:, 2]
    # Centerline points between the two levels, plus one point exactly at each level. Outside the traced range,
    # the centerline is extended by continuing its first/last segment (linear extrapolation).
    z_new = np.concatenate([[z_bottom], z[(z > z_bottom) & (z < z_top)], [z_top]])
    points = interp1d(z, centerline, axis=0, fill_value='extrapolate')(z_new)
    return np.sum(np.linalg.norm(np.diff(points, axis=0), axis=1))


def main():
    parser = argparse.ArgumentParser(description='Compute the spinal cord length (PMJ to conus) along the manual '
                                                 'centerline on the sagittal localizer.')
    parser.add_argument('-i', required=True,
                        help='Folder with the manual labels (sub-*/ses-*/anat/*_label-centerline.csv and '
                             '*_label-PMJtip_dlabel.nii.gz), typically derivatives/labels.')
    parser.add_argument('-o', help='Output CSV file. Default: <i>/cord_length.csv')
    parser.add_argument('-smooth', type=int, default=0,
                        help='Smooth the centerline with a moving average of this many points (one point per slice) '
                             'before computing the length, e.g., 5 for ~10 mm on the 1.95 mm localizer slices. '
                             'Default: 0 (no smoothing).')
    args = parser.parse_args()

    rows = []
    for fname_centerline in sorted(glob.glob(os.path.join(args.i, 'sub-*', 'ses-*', 'anat',
                                                          '*_label-centerline.csv'))):
        fname_labels = fname_centerline.replace('_label-centerline.csv', '_label-PMJtip_dlabel.nii.gz')
        name = os.path.basename(fname_centerline).replace('_label-centerline.csv', '')
        print(f'Processing {name}')
        if not os.path.exists(fname_labels):
            print(f'  {fname_labels} not found, skipping.')
            continue

        centerline = np.loadtxt(fname_centerline, delimiter=',', ndmin=2)
        img_labels = Image(fname_labels)
        z_pmj = get_label_z(img_labels, PMJ_LABEL)
        z_conus = get_label_z(img_labels, CONUS_LABEL)
        if z_pmj is None or z_conus is None:
            print('  Skipping.')
            continue

        z_bottom, z_top = sorted([z_conus, z_pmj])
        length = compute_length(centerline, z_bottom, z_top, smooth=args.smooth)
        # How far the centerline had to be extended to reach the PMJ and the conus levels
        z = centerline[:, 2]
        extrap = max(0.0, z_top - z.max()) + max(0.0, z.min() - z_bottom)

        print(f'  Cord length = {length:.1f} mm (straight S-I distance {z_top - z_bottom:.1f} mm)')
        if extrap > 3:
            print(f'  WARNING: centerline extended by {extrap:.0f} mm beyond its traced range.')
        rows.append({'participant_id': name.split('_')[0],
                     'session_id': name.split('_')[1],
                     'cord_length_mm': length,
                     'si_distance_mm': z_top - z_bottom,
                     'centerline_extrap_mm': extrap})

    fname_out = args.o or os.path.join(args.i, 'cord_length.csv')
    pd.DataFrame(rows).to_csv(fname_out, index=False, float_format='%.2f')
    print(f'Saved {fname_out}')


if __name__ == '__main__':
    main()
