"""
This script compares the spinal cord length (PMJ to conus, from 02_compute_cord_length.py) with the body height and
with the lumbosacral spinal level spans (L1-S2 and L1-L5), and summarizes the cord length by sex.

Note that the cord length and the L1-S2/L1-L5 spans measure different things (whole cord vs lumbosacral levels); the
comparison is a cross-check, not a validation.

Input:
    - cord_length.csv generated by 02_compute_cord_length.py
    - Excel file with the 'Spinal level heights (mm)' sheet (columns 'Participants' and 'L1' to 'S2', in mm) and the
      'Demographics' sheet (columns 'Participant', 'Sex', 'Weight (kg)' and 'Height (cm)')

Output (saved to the same folder as the input CSV):
    - cord_length_vs_spinal_levels.csv: cord length, L1-S2 and L1-L5 spans, body height, weight, sex and BMI per subject
    - cord_length_comparison.png: cord length vs body height, L1-S2 span and L1-L5 span, with the Pearson correlation

Example:
    python 03_correlation_cord_length.py -i cord_length.csv -xlsx spinal_level_heights_top_L1-bottom_S2.xlsx

Authors: Elia Rochiccioli, Jan Valosek
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

LEVELS = ['L1', 'L2', 'L3', 'L4', 'L5', 'S1', 'S2']


def load_excel(fname):
    """
    Load the L1-S2 and L1-L5 spans and the demographics from the Excel file.
    :param fname: path to the Excel file
    :return: DataFrame with one row per subject
    """
    # Spinal level heights; the span is the sum of the level heights (only subjects with all levels)
    levels = pd.read_excel(fname, sheet_name='Spinal level heights (mm)')
    levels = levels[levels['Participants'].astype(str).str.startswith('sub-')]
    levels[LEVELS] = levels[LEVELS].apply(pd.to_numeric, errors='coerce')
    levels = levels.dropna(subset=LEVELS)
    spans = pd.DataFrame({'participant_id': levels['Participants'],
                          'L1_S2_span_mm': levels[LEVELS].sum(axis=1).round(1),
                          'L1_L5_span_mm': levels[LEVELS[:5]].sum(axis=1).round(1)})

    demographics = pd.read_excel(fname, sheet_name='Demographics')
    demographics = pd.DataFrame({'participant_id': demographics['Participant'],
                                 'body_height_cm': pd.to_numeric(demographics['Height (cm)'], errors='coerce'),
                                 'weight_kg': pd.to_numeric(demographics['Weight (kg)'], errors='coerce'),
                                 'sex': demographics['Sex'].str.strip().str.lower()})
    demographics['bmi'] = (demographics['weight_kg'] / (demographics['body_height_cm'] / 100) ** 2).round(1)

    return demographics.merge(spans, on='participant_id', how='left')


def main():
    parser = argparse.ArgumentParser(description='Compare the spinal cord length with body height and lumbosacral '
                                                 'spinal level spans.')
    parser.add_argument('-i', required=True, help='cord_length.csv generated by 02_compute_cord_length.py')
    parser.add_argument('-xlsx', required=True,
                        help='Excel file with the "Spinal level heights (mm)" and "Demographics" sheets')
    args = parser.parse_args()
    path_out = os.path.dirname(os.path.abspath(args.i))

    df = pd.read_csv(args.i)[['participant_id', 'cord_length_mm']]
    df = df.merge(load_excel(args.xlsx), on='participant_id', how='left').sort_values('participant_id')
    df = df[['participant_id', 'cord_length_mm', 'L1_S2_span_mm', 'L1_L5_span_mm', 'body_height_cm', 'weight_kg',
             'sex', 'bmi']]
    fname_csv = os.path.join(path_out, 'cord_length_vs_spinal_levels.csv')
    df.to_csv(fname_csv, index=False)
    print(f'Saved {fname_csv}')

    # Summary (mean ± SD)
    cord = df['cord_length_mm']
    print(f'\nCord length: {cord.mean():.1f} ± {cord.std():.1f} mm (range {cord.min():.0f}-{cord.max():.0f}, '
          f'n={len(cord)})')
    for sex, group in df.groupby('sex'):
        print(f'  {sex}: {group["cord_length_mm"].mean():.1f} ± {group["cord_length_mm"].std():.1f} mm '
              f'(n={len(group)})')

    # Correlations and figure
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6))
    for ax, (col, label) in zip(axes, [('body_height_cm', 'Body height (cm)'),
                                       ('L1_S2_span_mm', 'L1–S2 span (mm)'),
                                       ('L1_L5_span_mm', 'L1–L5 span (mm)')]):
        data = df[[col, 'cord_length_mm']].dropna()
        x, y = data[col], data['cord_length_mm']
        r, p = stats.pearsonr(x, y)
        print(f'Cord length vs {col}: r={r:+.2f}, p={p:.3f}, n={len(data)}')

        ax.scatter(x, y, s=42, color='#2c7fb8', edgecolor='white', zorder=3)
        slope, intercept = np.polyfit(x, y, 1)
        x_fit = np.linspace(x.min(), x.max(), 50)
        ax.plot(x_fit, intercept + slope * x_fit, color='#d95f02', lw=1.8)
        ax.set_xlabel(label)
        ax.set_ylabel('Cord length PMJ→conus (mm)')
        ax.set_title(f'vs {label.split(" (")[0]}\nr={r:+.2f}{"*" if p < 0.05 else ""} (p={p:.3f}), n={len(data)}',
                     fontsize=9)
        ax.grid(alpha=0.25)
    plt.suptitle(f'Cord length (PMJ→conus), n={len(df)} participants', fontsize=11, y=1.03)
    plt.tight_layout()
    fname_png = os.path.join(path_out, 'cord_length_comparison.png')
    plt.savefig(fname_png, dpi=140, bbox_inches='tight')
    print(f'Saved {fname_png}')


if __name__ == '__main__':
    main()
